apiVersion: apps/v1
kind: Deployment
metadata:
  name: case-change-deploy          
  labels:
    app: case-change                
spec:
  replicas: 3
  selector:
    matchLabels:
      project: cd
  template:
    metadata:
      labels:
        project: cd
    spec:
      containers:
      - name: cd-case-change        
        image: 88tima/case_change:latest
        ports:
          - containerPort: 5000
